"""add razorpay workspace fields

Revision ID: 4e6d5b87f4d6
Revises: 0003
Create Date: 2026-05-19 12:56:13.418829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e6d5b87f4d6'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_events_fired_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_metrics_container_id'), table_name='metrics')
    op.drop_index(op.f('metrics_time_idx'), table_name='metrics')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('workspaces', sa.Column('razorpay_customer_id', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('workspaces', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'current_period_end')
    op.drop_column('workspaces', 'subscription_status')
    op.drop_column('workspaces', 'razorpay_subscription_id')
    op.drop_column('workspaces', 'razorpay_customer_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('metrics_time_idx'), 'metrics', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('ix_metrics_container_id'), 'metrics', ['container_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('razorpay_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('razorpay_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('subscriptions_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey')),
    sa.UniqueConstraint('workspace_id', name=op.f('subscriptions_workspace_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('metric', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fired_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], name=op.f('alert_events_container_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('alert_events_rule_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_events_pkey'))
    )
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_fired_at'), 'alert_events', ['fired_at'], unique=False)
    # ### end Alembic commands ###
